---
# main.yml tasks for package_updates role

# ---------------- Package Updates -------------------------
- name: Update all packages to latest versions
  apt:
    name: "*"
    state: latest
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Debian' 

- name: Update all packages to latest versions
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  become: yes
  when: ansible_os_family == 'RedHat'   
# ----------------------------------------------------------    